# Generated by Django 4.1.2 on 2022-10-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
