# Generated by Django 4.1.2 on 2022-10-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_seller_id_inventory_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
