# Generated by Django 4.1.2 on 2022-10-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_description_inventory_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
